[epnix.buildConfig]
# Put the name and version of your EPICS distribution here:
# ---
flavor = "custom"
version = "0.0.1"

[epnix.epics-base]
# You can choose the version of EPICS-base here:
# ---
#releaseBranch = "3" # Defaults to "7"

[epnix.support]
# Add one of the supported modules through its own option:
# ---
#StreamDevice.enable = true

# Or by specfying it here:
# ---
#modules = [ "pkgs.epnix.support.calc" ]

[epnix.applications]
# Add your applications:
# ---
#apps = [
#	"inputs.exampleApp"
#]

[epnix.boot]
# And your iocBoot directories:
# ---
#iocBoots = [
#	"./iocBoot/iocexample"
#]

# You can specify environment variables in your development shell like this:
# ---

#[[devShell.env]]
#name = "EPICS_CA_ADDR_LIST"
#value = "localhost"

#[[devShell.env]]
#name = "MY_VARIABLE"
#value = "the_value"
