workflow:
  auto_cancel:
    on_new_commit: interruptible

default:
  interruptible: true
  tags:
    - nix

variables:
  NIX_BUILD_FLAGS: "--no-update-lock-file --print-build-logs --show-trace"

before_script:
  - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@drf-gitlab.cea.fr".insteadOf "ssh://git@drf-gitlab.cea.fr"

run_checks:
  stage: test
  script:
    - nix flake check $NIX_BUILD_FLAGS

editorconfig:
  stage: test
  script:
    - nix run 'nixpkgs#eclint' --inputs-from .

formatting:
  stage: test
  script:
    - nix fmt -- --check .

manpages:
  stage: deploy
  script:
    - nix build $NIX_BUILD_FLAGS '.#manpages'
    - cp -Lr ./result manpages
  artifacts:
    name: "manpages-$CI_COMMIT_REF_SLUG"
    paths:
      - manpages

pages:
  stage: deploy
  script:
    - nix build $NIX_BUILD_FLAGS '.#book'
    - cp -Lr ./result public
  artifacts:
    name: "book"
    paths:
      - public
  dependencies: []
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
