default:
  tags:
    - nix

before_script:
  - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@drf-gitlab.cea.fr".insteadOf "ssh://git@drf-gitlab.cea.fr"

run_checks:
  stage: test
  script:
    - nix flake check --no-update-lock-file --print-build-logs --show-trace
