[tool.poetry]
name = "psu-simulator"
version = "0.1.0"
description = "A power supply simulator for the StreamDevice tutorial"
authors = ["Rémi NICOLE <remi.nicole@cea.fr>"]

[tool.poetry.scripts]
psu-simulator = "psu_simulator:main"

[tool.poetry.dependencies]
python = ">=3.7.0"
click = "^8.1.7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
select = ["ALL"]
