name: "Check EditorConfig"

permissions: read-all

on:
  push:
  pull_request:

jobs:
  editorconfig:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
    - uses: cachix/install-nix-action@6004951b182f8860210c8d6f0d808ec5b1a33d28 # v25
    - name: "Check EditorConfig"
      run: nix run 'nixpkgs#eclint' --inputs-from .
