name: "Check EditorConfig"

permissions: read-all

on:
  pull_request_target:
    types: [opened, synchronize, reopened, edited]

jobs:
  editorconfig:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        persist-credentials: false
    - uses: cachix/install-nix-action@3715ab1a11cac9e991980d7b4a28d80c7ebdd8f9 # v27
    - name: "Check EditorConfig"
      run: nix run 'nixpkgs#eclint' --inputs-from .
