name: "Check Formatting"

permissions: read-all

on:
  push:
  pull_request:

jobs:
  alejandra:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
    - uses: cachix/install-nix-action@ba0dd844c9180cbf77aa72a116d6fbc515d0e87b # v27
    - name: "Check Formatting"
      run: nix fmt -- --check .
