name: "Check Formatting"

permissions: read-all

on:
  pull_request:

jobs:
  alejandra:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      with:
        persist-credentials: false
    - uses: cachix/install-nix-action@3715ab1a11cac9e991980d7b4a28d80c7ebdd8f9 # v27
    - name: "Check Formatting"
      run: nix fmt -- --check .
