name: "Check Formatting"

permissions: read-all

on:
  pull_request_target:
    types: [opened, synchronize, reopened, edited]

jobs:
  alejandra:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        persist-credentials: false
    - uses: cachix/install-nix-action@ba0dd844c9180cbf77aa72a116d6fbc515d0e87b # v27
    - name: "Check Formatting"
      run: nix fmt -- --check .
